name: Node.js I, Netlify Actions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - run: npm run test --if-present

  deploy:
    runs-on: self-hosted
    needs: [build]
  
    steps:
    - name: Netlify Actions
    # You may pin to the exact commit or the version.
    # uses: nwtgck/actions-netlify@b7c1504e00c6b8a249d1848cc1b522a4865eed99
      uses: nwtgck/actions-netlify@v1.2.3
      with:
        # Publish directory
        publish-dir: './public'
        # Custom deploy message for Netlify
        deploy-message: "Deploy from GitHub Actions"
        # Production branch
        production-branch: main
        # Indicate wether to deploy production build
        production-deploy: false
        # Enable pull request comment
        enable-pull-request-comment: false
        # Enable commit comment
        enable-commit-comment: false
        # Enable GitHub commit status
        enable-commit-status: false
        # Overwrites pull request comment
        overwrites-pull-request-comment: false
        # Path to netlify.toml
        fails-without-credentials: false  
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}        
